# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: kubernetes-the-hard-way
description: "A Pulumi implementation of Kelsey Hightower's Kubernetes the Hard Way"
repository: https://github.com/UnstoppableMango/pulumi-kubernetes-the-hard-way
keywords:
  - pulumi
  - command
  - tls
  - kubernetes
  - category/utility
  - kind/component
resources:
  kubernetes-the-hard-way:index:Certificate:
    isComponent: true
    inputProperties:
      algorithm:
        type: string
        description: Name of the algorithm to use when generating the private key.
      ecdsaCurve:
        type: string
        description: When `algorithm` is `ECDSA`, the name of the elliptic curve to use.
      rsaBits:
        type: integer
        description: When `algorithm` is `RSA`, the size of the generated RSA key, in bits.
      dnsNames:
        type: array
        items:
          type: string
        description: List of DNS names for which a certificate is being requested.
      earlyRenewalHours:
        type: integer
        description: TODO
      ipAddresses:
        type: array
        items:
          type: string
        description: List of IP addresses for which a certificate is being requested.
      setAuthorityKeyId:
        type: boolean
        description: Should the generated certificate include an authority key identifier.
      setSubjectKeyId:
        type: boolean
        description: Should the generated certificate include a subject key identifier.
      uris:
        type: array
        items:
          type: string
        description: List of URIs for which a certificate is being requested.
      validityPeriodHours:
        type: integer
        description: Number of hours, after initial issuing, that the certificate will remain valid.
      allowedUses:
        type: array
        items:
          type: string
      caCertPem:
        type: string
      caPrivateKeyPem:
        type: string
      isCaCertificate:
        type: boolean
      subject:
        $ref: "/tls/v5.0.1/schema.json#/types/tls:index/CertRequestSubject:CertRequestSubject"
    requiredInputs:
      - allowedUses
      - caCertPem
      - caPrivateKeyPem
      - validityPeriodHours
    properties:
      cert:
        $ref: "/tls/v5.0.1/schema.json#/resources/tls:index/locallySignedCert:LocallySignedCert"
      certPem:
        type: string
      csr:
        $ref: "/tls/v5.0.1/schema.json#/resources/tls:index/certRequest:CertRequest"
      key:
        $ref: "/tls/v5.0.1/schema.json#/resources/tls:index/privateKey:PrivateKey"
      keyPem:
        type: string
    required:
      - cert
      - certPem
      - csr
      - key
      - keyPem
functions:
  kubernetes-the-hard-way:index:getAdminCertificate:
    description: Creates a Certificate configured for the cluster admin.
    inputs:
      properties:
        algorithm:
          type: string
          description: Name of the algorithm to use when generating the private key.
        ecdsaCurve:
          type: string
          description: When `algorithm` is `ECDSA`, the name of the elliptic curve to use.
        rsaBits:
          type: integer
          description: When `algorithm` is `RSA`, the size of the generated RSA key, in bits.
        dnsNames:
          type: array
          items:
            type: string
          description: List of DNS names for which a certificate is being requested.
        earlyRenewalHours:
          type: integer
          description: TODO
        ipAddresses:
          type: array
          items:
            type: string
          description: List of IP addresses for which a certificate is being requested.
        setAuthorityKeyId:
          type: boolean
          description: Should the generated certificate include an authority key identifier.
        setSubjectKeyId:
          type: boolean
          description: Should the generated certificate include a subject key identifier.
        uris:
          type: array
          items:
            type: string
          description: List of URIs for which a certificate is being requested.
        validityPeriodHours:
          type: integer
          description: Number of hours, after initial issuing, that the certificate will remain valid.
        allowedUses:
          type: array
          items:
            type: string
        isCaCertificate:
          type: boolean
        subject:
          $ref: "/tls/v5.0.1/schema.json#/types/tls:index/CertRequestSubject:CertRequestSubject"
      required:
        - allowedUses
        - validityPeriodHours
    outputs:
      properties:
        cert:
          $ref: "#/resources/kubernetes-the-hard-way:index:Certificate"
      required:
        - cert
language:
  csharp:
    rootNamespace: UnMango # TODO: Name that works
    dictionaryConstructors: true
    packageReferences:
      Pulumi: 3.*
      Pulumi.Command: 0.9.*
      Pulumi.Tls: 5.*
  go:
    generateResourceContainerTypes: true
    importBasePath: github.com/unstoppablemango/pulumi-kubernetes-the-hard-way/sdk/go/kubernetes-the-hard-way
  nodejs:
    packageName: "@unmango/pulumi-kubernetes-the-hard-way"
    dependencies:
      "@pulumi/pulumi": "^3.0.0"
      "@pulumi/command": "^0.9.2"
      "@pulumi/tls": "^5.0.1"
    devDependencies:
      typescript: "^3.7.0"
  python:
    pyproject:
      enabled: true
    requires:
      pulumi: ">=3.0.0,<4.0.0"
      pulumi-command: ">=0.9.2,<1.0.0"
      pulumi-tls: ">=5.0.1,<6.0.0"
  java:
    basePackage: com.unmango # TODO: Name that works
    buildFiles: gradle
    gradleNexusPublishPluginVersion: 1.1.0
    dependencies:
      com.google.code.findbugs:jsr305: 3.0.2
      com.google.code.gson:gson: 2.8.9
      com.pulumi:pulumi: 0.9.9
      com.pulumi:command: 0.9.2
      com.pulumi:tls: 5.0.1
