# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: kubernetes-the-hard-way
resources:
  kubernetes-the-hard-way:index:RemoteFile:
    isComponent: true
    inputProperties:
      connection:
        "$ref": "/command/v0.9.0/schema.json#/types/command:remote:Connection"
        description: The connection details.
      content:
        type: string
        description: The content of the file.
      path:
        type: string
        description: The path to the file on the remote host.
    requiredInputs:
      - connection
      - content
      - path
    properties:
      command:
        "$ref": "/command/v0.9.0/schema.json#/resources/command:remote:Command"
        description: The command resource.
    required:
      - command
language:
  csharp:
    rootNamespace: UnMango
    packageReferences:
      Pulumi: 3.*
      Pulumi.Command: 0.9.*
      Pulumi.Tls: 5.*
  go:
    generateResourceContainerTypes: true
    importBasePath: github.com/unstoppablemango/pulumi-kubernetes-the-hard-way/sdk/go/kubernetes-the-hard-way
  nodejs:
    packageName: '@unmango/pulumi-kubernetes-the-hard-way'
    dependencies:
      "@pulumi/command": "^0.9.0"
      "@pulumi/tls": "^5.0.0"
    devDependencies:
      typescript: "^3.7.0"
  python:
    requires:
      pulumi: ">=3.0.0,<4.0.0"
      pulumi-command: ">=0.9.0,<1.0.0"
      pulumi-tls: ">=5.0.0,<6.0.0"
