// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace UnMango.KubernetesTheHardWay.Config
{
    /// <summary>
    /// Kubeconfig type
    /// </summary>
    [EnumType]
    public readonly struct KubeconfigType : IEquatable<KubeconfigType>
    {
        private readonly string _value;

        private KubeconfigType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static KubeconfigType Worker { get; } = new KubeconfigType("worker");
        public static KubeconfigType Kube_proxy { get; } = new KubeconfigType("kube-proxy");
        public static KubeconfigType Kube_controller_manager { get; } = new KubeconfigType("kube-controller-manager");
        public static KubeconfigType Kube_scheduler { get; } = new KubeconfigType("kube-scheduler");
        public static KubeconfigType Admin { get; } = new KubeconfigType("admin");

        public static bool operator ==(KubeconfigType left, KubeconfigType right) => left.Equals(right);
        public static bool operator !=(KubeconfigType left, KubeconfigType right) => !left.Equals(right);

        public static explicit operator string(KubeconfigType value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is KubeconfigType other && Equals(other);
        public bool Equals(KubeconfigType other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
