// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.unmango.kubernetesthehardway.remote;

import com.pulumi.command.remote.outputs.Connection;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.unmango.kubernetesthehardway.Utilities;
import com.unmango.kubernetesthehardway.remote.KubeSchedulerInstallArgs;
import com.unmango.kubernetesthehardway.remote.enums.Architecture;
import com.unmango.kubernetesthehardway.tools.Mkdir;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Installs kube-scheduler on a remote system.
 * 
 */
@ResourceType(type="kubernetes-the-hard-way:remote:KubeSchedulerInstall")
public class KubeSchedulerInstall extends com.pulumi.resources.ComponentResource {
    /**
     * The kube-scheduler CPU architecture.
     * 
     */
    @Export(name="architecture", refs={Architecture.class}, tree="[0]")
    private Output<Architecture> architecture;

    /**
     * @return The kube-scheduler CPU architecture.
     * 
     */
    public Output<Architecture> architecture() {
        return this.architecture;
    }
    @Export(name="archiveName", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> archiveName;

    public Output<Optional<String>> archiveName() {
        return Codegen.optional(this.archiveName);
    }
    /**
     * The connection details.
     * 
     */
    @Export(name="connection", refs={Connection.class}, tree="[0]")
    private Output<Connection> connection;

    /**
     * @return The connection details.
     * 
     */
    public Output<Connection> connection() {
        return this.connection;
    }
    /**
     * Directory to install the `etcd` and `etcdctl` binaries.
     * 
     */
    @Export(name="directory", refs={String.class}, tree="[0]")
    private Output<String> directory;

    /**
     * @return Directory to install the `etcd` and `etcdctl` binaries.
     * 
     */
    public Output<String> directory() {
        return this.directory;
    }
    @Export(name="mkdir", refs={Mkdir.class}, tree="[0]")
    private Output</* @Nullable */ Mkdir> mkdir;

    public Output<Optional<Mkdir>> mkdir() {
        return Codegen.optional(this.mkdir);
    }
    /**
     * The version of kube-scheduler to install.
     * 
     */
    @Export(name="version", refs={String.class}, tree="[0]")
    private Output<String> version;

    /**
     * @return The version of kube-scheduler to install.
     * 
     */
    public Output<String> version() {
        return this.version;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public KubeSchedulerInstall(String name) {
        this(name, KubeSchedulerInstallArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public KubeSchedulerInstall(String name, KubeSchedulerInstallArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public KubeSchedulerInstall(String name, KubeSchedulerInstallArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        super("kubernetes-the-hard-way:remote:KubeSchedulerInstall", name, args == null ? KubeSchedulerInstallArgs.Empty : args, makeResourceOptions(options, Codegen.empty()), true);
    }

    private static com.pulumi.resources.ComponentResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.ComponentResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.ComponentResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.ComponentResourceOptions.merge(defaultOptions, options, id);
    }

}
