// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { DownloadArgs } from "./download";
export type Download = import("./download").Download;
export const Download: typeof import("./download").Download = null as any;
utilities.lazyLoad(exports, ["Download"], () => require("./download"));

export { FileArgs } from "./file";
export type File = import("./file").File;
export const File: typeof import("./file").File = null as any;
utilities.lazyLoad(exports, ["File"], () => require("./file"));

export { InstallCertArgs, InstallCertResult, InstallCertOutputArgs } from "./installCert";
export const installCert: typeof import("./installCert").installCert = null as any;
export const installCertOutput: typeof import("./installCert").installCertOutput = null as any;
utilities.lazyLoad(exports, ["installCert","installCertOutput"], () => require("./installCert"));

export { InstallControlPlaneArgs } from "./installControlPlane";
export const installControlPlane: typeof import("./installControlPlane").installControlPlane = null as any;
utilities.lazyLoad(exports, ["installControlPlane"], () => require("./installControlPlane"));

export { InstallKeyArgs, InstallKeyResult, InstallKeyOutputArgs } from "./installKey";
export const installKey: typeof import("./installKey").installKey = null as any;
export const installKeyOutput: typeof import("./installKey").installKeyOutput = null as any;
utilities.lazyLoad(exports, ["installKey","installKeyOutput"], () => require("./installKey"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes-the-hard-way:remote:Download":
                return new Download(name, <any>undefined, { urn })
            case "kubernetes-the-hard-way:remote:File":
                return new File(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("kubernetes-the-hard-way", "remote", _module)
