// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

import {Systemctl} from "../tools";

/**
 * Starts etcd on a remote system.
 */
export class StartEtcd extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'kubernetes-the-hard-way:remote:StartEtcd';

    /**
     * Returns true if the given object is an instance of StartEtcd.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StartEtcd {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StartEtcd.__pulumiType;
    }

    /**
     * The daemon-reload command.
     */
    public /*out*/ readonly daemonReload!: pulumi.Output<Systemctl>;
    /**
     * The enable command.
     */
    public /*out*/ readonly enable!: pulumi.Output<Systemctl>;
    /**
     * The start command.
     */
    public /*out*/ readonly start!: pulumi.Output<Systemctl>;

    /**
     * Create a StartEtcd resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: StartEtcdArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["daemonReload"] = undefined /*out*/;
            resourceInputs["enable"] = undefined /*out*/;
            resourceInputs["start"] = undefined /*out*/;
        } else {
            resourceInputs["daemonReload"] = undefined /*out*/;
            resourceInputs["enable"] = undefined /*out*/;
            resourceInputs["start"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(StartEtcd.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a StartEtcd resource.
 */
export interface StartEtcdArgs {
}
