// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.KubernetesTheHardWay.Config.Inputs
{

    public sealed class KubeletConfigurationAuthenticationx509Args : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// TODO
        /// </summary>
        [Input("clientCAFile", required: true)]
        public Input<string> ClientCAFile { get; set; } = null!;

        public KubeletConfigurationAuthenticationx509Args()
        {
        }
        public static new KubeletConfigurationAuthenticationx509Args Empty => new KubeletConfigurationAuthenticationx509Args();
    }
}
