# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from .etcd_configuration import EtcdConfiguration
from .etcd_install import EtcdInstall
from .start_etcd import StartEtcd
import pulumi_command

__all__ = ['ProvisionEtcdArgs', 'ProvisionEtcd']

@pulumi.input_type
class ProvisionEtcdArgs:
    def __init__(__self__, *,
                 connection: pulumi.Input['pulumi_command.remote.ConnectionArgs'],
                 configuration: Optional[pulumi.Input['EtcdConfiguration']] = None):
        """
        The set of arguments for constructing a ProvisionEtcd resource.
        :param pulumi.Input['pulumi_command.remote.ConnectionArgs'] connection: The parameters with which to connect to the remote host.
        :param pulumi.Input['EtcdConfiguration'] configuration: Etcd configuration.
        """
        pulumi.set(__self__, "connection", connection)
        if configuration is not None:
            pulumi.set(__self__, "configuration", configuration)

    @property
    @pulumi.getter
    def connection(self) -> pulumi.Input['pulumi_command.remote.ConnectionArgs']:
        """
        The parameters with which to connect to the remote host.
        """
        return pulumi.get(self, "connection")

    @connection.setter
    def connection(self, value: pulumi.Input['pulumi_command.remote.ConnectionArgs']):
        pulumi.set(self, "connection", value)

    @property
    @pulumi.getter
    def configuration(self) -> Optional[pulumi.Input['EtcdConfiguration']]:
        """
        Etcd configuration.
        """
        return pulumi.get(self, "configuration")

    @configuration.setter
    def configuration(self, value: Optional[pulumi.Input['EtcdConfiguration']]):
        pulumi.set(self, "configuration", value)


class ProvisionEtcd(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 configuration: Optional[pulumi.Input['EtcdConfiguration']] = None,
                 connection: Optional[pulumi.Input[pulumi.InputType['pulumi_command.remote.ConnectionArgs']]] = None,
                 __props__=None):
        """
        Starts etcd on a remote system.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input['EtcdConfiguration'] configuration: Etcd configuration.
        :param pulumi.Input[pulumi.InputType['pulumi_command.remote.ConnectionArgs']] connection: The parameters with which to connect to the remote host.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ProvisionEtcdArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Starts etcd on a remote system.

        :param str resource_name: The name of the resource.
        :param ProvisionEtcdArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProvisionEtcdArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 configuration: Optional[pulumi.Input['EtcdConfiguration']] = None,
                 connection: Optional[pulumi.Input[pulumi.InputType['pulumi_command.remote.ConnectionArgs']]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProvisionEtcdArgs.__new__(ProvisionEtcdArgs)

            __props__.__dict__["configuration"] = configuration
            if connection is None and not opts.urn:
                raise TypeError("Missing required property 'connection'")
            __props__.__dict__["connection"] = connection
            __props__.__dict__["install"] = None
            __props__.__dict__["start"] = None
        super(ProvisionEtcd, __self__).__init__(
            'kubernetes-the-hard-way:remote:ProvisionEtcd',
            resource_name,
            __props__,
            opts,
            remote=True)

    @property
    @pulumi.getter
    def configuration(self) -> pulumi.Output['EtcdConfiguration']:
        """
        Etcd configuration.
        """
        return pulumi.get(self, "configuration")

    @property
    @pulumi.getter
    def connection(self) -> pulumi.Output['pulumi_command.remote.outputs.Connection']:
        """
        The parameters with which to connect to the remote host.
        """
        return pulumi.get(self, "connection")

    @property
    @pulumi.getter
    def install(self) -> pulumi.Output['EtcdInstall']:
        """
        Install etcd.
        """
        return pulumi.get(self, "install")

    @property
    @pulumi.getter
    def start(self) -> pulumi.Output[Optional['StartEtcd']]:
        """
        Start etcd
        """
        return pulumi.get(self, "start")

