// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

import * as pulumiCommand from "@pulumi/command";

/**
 * Abstraction over the `etcdctl` utility on a remote system.
 */
export class Etcdctl extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'kubernetes-the-hard-way:tools:Etcdctl';

    /**
     * Returns true if the given object is an instance of Etcdctl.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Etcdctl {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Etcdctl.__pulumiType;
    }

    /**
     * Represents the command run on the remote system.
     */
    public /*out*/ readonly command!: pulumi.Output<pulumiCommand.remote.Command | undefined>;
    /**
     * Connection details for the remote system.
     */
    public readonly connection!: pulumi.Output<pulumiCommand.types.output.remote.Connection | undefined>;

    /**
     * Create a Etcdctl resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EtcdctlArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.connection === undefined) && !opts.urn) {
                throw new Error("Missing required property 'connection'");
            }
            resourceInputs["caCert"] = args ? args.caCert : undefined;
            resourceInputs["cert"] = args ? args.cert : undefined;
            resourceInputs["commands"] = args ? args.commands : undefined;
            resourceInputs["connection"] = args ? (args.connection ? pulumi.output(args.connection).apply(pulumiCommand.types.input.remote.connectionArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["endpoints"] = args ? args.endpoints : undefined;
            resourceInputs["key"] = args ? args.key : undefined;
            resourceInputs["command"] = undefined /*out*/;
        } else {
            resourceInputs["command"] = undefined /*out*/;
            resourceInputs["connection"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Etcdctl.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Etcdctl resource.
 */
export interface EtcdctlArgs {
    caCert?: pulumi.Input<string>;
    cert?: pulumi.Input<string>;
    commands?: pulumi.Input<pulumi.Input<enums.tools.EtcdctlCommand>[]>;
    /**
     * Connection details for the remote system.
     */
    connection: pulumi.Input<pulumiCommand.types.input.remote.ConnectionArgs>;
    endpoints?: pulumi.Input<string>;
    key?: pulumi.Input<string>;
}
