// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.unmango.kubernetesthehardway.tools;

import com.pulumi.command.remote.Command;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.unmango.kubernetesthehardway.Utilities;
import com.unmango.kubernetesthehardway.tools.MkdirArgs;
import java.lang.Boolean;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * Represents the `mkdir` utility.
 * 
 */
@ResourceType(type="kubernetes-the-hard-way:tools:Mkdir")
public class Mkdir extends com.pulumi.resources.ComponentResource {
    /**
     * The remote command.
     * 
     */
    @Export(name="command", refs={Command.class}, tree="[0]")
    private Output<Command> command;

    /**
     * @return The remote command.
     * 
     */
    public Output<Command> command() {
        return this.command;
    }
    /**
     * The fully qualified path of the directory on the remote system.
     * 
     */
    @Export(name="directory", refs={String.class}, tree="[0]")
    private Output<String> directory;

    /**
     * @return The fully qualified path of the directory on the remote system.
     * 
     */
    public Output<String> directory() {
        return this.directory;
    }
    /**
     * Corresponds to the `--parents` option.
     * 
     */
    @Export(name="parents", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> parents;

    /**
     * @return Corresponds to the `--parents` option.
     * 
     */
    public Output<Boolean> parents() {
        return this.parents;
    }
    /**
     * Remove the created directory when the `Mkdir` resource is deleted or updated.
     * 
     */
    @Export(name="removeOnDelete", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> removeOnDelete;

    /**
     * @return Remove the created directory when the `Mkdir` resource is deleted or updated.
     * 
     */
    public Output<Boolean> removeOnDelete() {
        return this.removeOnDelete;
    }
    /**
     * The command&#39;s stderr.
     * 
     */
    @Export(name="stderr", refs={String.class}, tree="[0]")
    private Output<String> stderr;

    /**
     * @return The command&#39;s stderr.
     * 
     */
    public Output<String> stderr() {
        return this.stderr;
    }
    /**
     * The command&#39;s stdout.
     * 
     */
    @Export(name="stdout", refs={String.class}, tree="[0]")
    private Output<String> stdout;

    /**
     * @return The command&#39;s stdout.
     * 
     */
    public Output<String> stdout() {
        return this.stdout;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Mkdir(String name) {
        this(name, MkdirArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Mkdir(String name, MkdirArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Mkdir(String name, MkdirArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        super("kubernetes-the-hard-way:tools:Mkdir", name, args == null ? MkdirArgs.Empty : args, makeResourceOptions(options, Codegen.empty()), true);
    }

    private static com.pulumi.resources.ComponentResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.ComponentResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.ComponentResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.ComponentResourceOptions.merge(defaultOptions, options, id);
    }

}
