// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package remote

import (
	"context"
	"reflect"

	"errors"
	pulumiCommand "github.com/pulumi/pulumi-command/sdk/go/command/remote"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/unstoppablemango/pulumi-kubernetes-the-hard-way/sdk/go/kubernetes-the-hard-way/internal"
	"github.com/unstoppablemango/pulumi-kubernetes-the-hard-way/sdk/go/kubernetes-the-hard-way/tools"
)

// Represents an etcd binary on a remote system.
type EtcdInstall struct {
	pulumi.ResourceState

	// The etcd CPU architecture.
	Architecture ArchitectureOutput `pulumi:"architecture"`
	// The name of the etcd release archive.
	ArchiveName pulumi.StringOutput `pulumi:"archiveName"`
	// The remote certificate authority file.
	CaFile FileOutput `pulumi:"caFile"`
	// The remote certificate file.
	CertFile FileOutput `pulumi:"certFile"`
	// The directory to store etcd configuration.
	ConfigurationDirectory pulumi.StringOutput `pulumi:"configurationDirectory"`
	// The command used to create the configuration directory.
	ConfigurationMkdir tools.MkdirOutput `pulumi:"configurationMkdir"`
	// The directory etcd will use.
	DataDirectory pulumi.StringOutput `pulumi:"dataDirectory"`
	// The command used to create the data directory.
	DataMkdir tools.MkdirOutput `pulumi:"dataMkdir"`
	// The etcd download operation.
	Download DownloadOutput `pulumi:"download"`
	// The directory where the etcd binary was downloaded to.
	DownloadDirectory pulumi.StringOutput `pulumi:"downloadDirectory"`
	// The operation to create the download directory.
	DownloadMkdir tools.MkdirOutput `pulumi:"downloadMkdir"`
	// The path to the etcd binary on the remote system.
	EtcdPath pulumi.StringOutput `pulumi:"etcdPath"`
	// The path to the etcdctl binary on the remote system.
	EtcdctlPath pulumi.StringOutput `pulumi:"etcdctlPath"`
	// Directory to install the `etcd` and `etcdctl` binaries.
	InstallDirectory pulumi.StringOutput `pulumi:"installDirectory"`
	// The operation to create the install directory.
	InstallMkdir tools.MkdirOutput `pulumi:"installMkdir"`
	// IP used to serve client requests and communicate with etcd peers.
	InternalIp pulumi.StringOutput `pulumi:"internalIp"`
	// The remote key file.
	KeyFile FileOutput `pulumi:"keyFile"`
	// The operation to move the etcd binary to the install directory.
	MvEtcd tools.MvOutput `pulumi:"mvEtcd"`
	// The operation to move the etcdctl binary to the install directory.
	MvEtcdctl tools.MvOutput `pulumi:"mvEtcdctl"`
	// The name of the resource.
	Name pulumi.StringOutput `pulumi:"name"`
	// The remote systemd service file.
	SystemdServiceFile FileOutput `pulumi:"systemdServiceFile"`
	// The tar operation.
	Tar tools.TarOutput `pulumi:"tar"`
	// The url used to download etcd.
	Url pulumi.StringOutput `pulumi:"url"`
	// The version of etcd downloaded.
	Version pulumi.StringOutput `pulumi:"version"`
}

// NewEtcdInstall registers a new resource with the given unique name, arguments, and options.
func NewEtcdInstall(ctx *pulumi.Context,
	name string, args *EtcdInstallArgs, opts ...pulumi.ResourceOption) (*EtcdInstall, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.CaPem == nil {
		return nil, errors.New("invalid value for required argument 'CaPem'")
	}
	if args.CertPem == nil {
		return nil, errors.New("invalid value for required argument 'CertPem'")
	}
	if args.Connection == nil {
		return nil, errors.New("invalid value for required argument 'Connection'")
	}
	if args.InternalIp == nil {
		return nil, errors.New("invalid value for required argument 'InternalIp'")
	}
	if args.KeyPem == nil {
		return nil, errors.New("invalid value for required argument 'KeyPem'")
	}
	if args.ConfigurationDirectory == nil {
		args.ConfigurationDirectory = pulumi.StringPtr("/etc/etcd")
	}
	args.Connection = args.Connection.ToConnectionOutput().ApplyT(func(v pulumiCommand.Connection) pulumiCommand.Connection { return *v.Defaults() }).(pulumiCommand.ConnectionOutput)
	if args.DataDirectory == nil {
		args.DataDirectory = pulumi.StringPtr("/var/lib/etcd")
	}
	if args.InstallDirectory == nil {
		args.InstallDirectory = pulumi.StringPtr("/usr/local/bin")
	}
	if args.SystemdDirectory == nil {
		args.SystemdDirectory = pulumi.StringPtr("/etc/system/systemd")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource EtcdInstall
	err := ctx.RegisterRemoteComponentResource("kubernetes-the-hard-way:remote:EtcdInstall", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type etcdInstallArgs struct {
	// The etcd CPU architecture.
	Architecture *Architecture `pulumi:"architecture"`
	// The PEM encoded CA data.
	CaPem string `pulumi:"caPem"`
	// The PEM encoded certificate data.
	CertPem string `pulumi:"certPem"`
	// The directory to store etcd configuration.
	ConfigurationDirectory *string `pulumi:"configurationDirectory"`
	// The connection details.
	Connection pulumiCommand.Connection `pulumi:"connection"`
	// The directory etcd will use.
	DataDirectory *string `pulumi:"dataDirectory"`
	// Temporary directory to download files to. Defaults to `/tmp/<random string>`.
	DownloadDirectory *string `pulumi:"downloadDirectory"`
	// Directory to install the `etcd` and `etcdctl` binaries.
	InstallDirectory *string `pulumi:"installDirectory"`
	// IP used to serve client requests and communicate with etcd peers.
	InternalIp string `pulumi:"internalIp"`
	// The PEM encoded key data.
	KeyPem string `pulumi:"keyPem"`
	// The systemd service file dirctory.
	SystemdDirectory *string `pulumi:"systemdDirectory"`
	// The version of etcd to install.
	Version *string `pulumi:"version"`
}

// The set of arguments for constructing a EtcdInstall resource.
type EtcdInstallArgs struct {
	// The etcd CPU architecture.
	Architecture ArchitecturePtrInput
	// The PEM encoded CA data.
	CaPem pulumi.StringInput
	// The PEM encoded certificate data.
	CertPem pulumi.StringInput
	// The directory to store etcd configuration.
	ConfigurationDirectory pulumi.StringPtrInput
	// The connection details.
	Connection pulumiCommand.ConnectionInput
	// The directory etcd will use.
	DataDirectory pulumi.StringPtrInput
	// Temporary directory to download files to. Defaults to `/tmp/<random string>`.
	DownloadDirectory pulumi.StringPtrInput
	// Directory to install the `etcd` and `etcdctl` binaries.
	InstallDirectory pulumi.StringPtrInput
	// IP used to serve client requests and communicate with etcd peers.
	InternalIp pulumi.StringInput
	// The PEM encoded key data.
	KeyPem pulumi.StringInput
	// The systemd service file dirctory.
	SystemdDirectory pulumi.StringPtrInput
	// The version of etcd to install.
	Version pulumi.StringPtrInput
}

func (EtcdInstallArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*etcdInstallArgs)(nil)).Elem()
}

type EtcdInstallInput interface {
	pulumi.Input

	ToEtcdInstallOutput() EtcdInstallOutput
	ToEtcdInstallOutputWithContext(ctx context.Context) EtcdInstallOutput
}

func (*EtcdInstall) ElementType() reflect.Type {
	return reflect.TypeOf((**EtcdInstall)(nil)).Elem()
}

func (i *EtcdInstall) ToEtcdInstallOutput() EtcdInstallOutput {
	return i.ToEtcdInstallOutputWithContext(context.Background())
}

func (i *EtcdInstall) ToEtcdInstallOutputWithContext(ctx context.Context) EtcdInstallOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EtcdInstallOutput)
}

// EtcdInstallArrayInput is an input type that accepts EtcdInstallArray and EtcdInstallArrayOutput values.
// You can construct a concrete instance of `EtcdInstallArrayInput` via:
//
//	EtcdInstallArray{ EtcdInstallArgs{...} }
type EtcdInstallArrayInput interface {
	pulumi.Input

	ToEtcdInstallArrayOutput() EtcdInstallArrayOutput
	ToEtcdInstallArrayOutputWithContext(context.Context) EtcdInstallArrayOutput
}

type EtcdInstallArray []EtcdInstallInput

func (EtcdInstallArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*EtcdInstall)(nil)).Elem()
}

func (i EtcdInstallArray) ToEtcdInstallArrayOutput() EtcdInstallArrayOutput {
	return i.ToEtcdInstallArrayOutputWithContext(context.Background())
}

func (i EtcdInstallArray) ToEtcdInstallArrayOutputWithContext(ctx context.Context) EtcdInstallArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EtcdInstallArrayOutput)
}

// EtcdInstallMapInput is an input type that accepts EtcdInstallMap and EtcdInstallMapOutput values.
// You can construct a concrete instance of `EtcdInstallMapInput` via:
//
//	EtcdInstallMap{ "key": EtcdInstallArgs{...} }
type EtcdInstallMapInput interface {
	pulumi.Input

	ToEtcdInstallMapOutput() EtcdInstallMapOutput
	ToEtcdInstallMapOutputWithContext(context.Context) EtcdInstallMapOutput
}

type EtcdInstallMap map[string]EtcdInstallInput

func (EtcdInstallMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*EtcdInstall)(nil)).Elem()
}

func (i EtcdInstallMap) ToEtcdInstallMapOutput() EtcdInstallMapOutput {
	return i.ToEtcdInstallMapOutputWithContext(context.Background())
}

func (i EtcdInstallMap) ToEtcdInstallMapOutputWithContext(ctx context.Context) EtcdInstallMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EtcdInstallMapOutput)
}

type EtcdInstallOutput struct{ *pulumi.OutputState }

func (EtcdInstallOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**EtcdInstall)(nil)).Elem()
}

func (o EtcdInstallOutput) ToEtcdInstallOutput() EtcdInstallOutput {
	return o
}

func (o EtcdInstallOutput) ToEtcdInstallOutputWithContext(ctx context.Context) EtcdInstallOutput {
	return o
}

// The etcd CPU architecture.
func (o EtcdInstallOutput) Architecture() ArchitectureOutput {
	return o.ApplyT(func(v *EtcdInstall) ArchitectureOutput { return v.Architecture }).(ArchitectureOutput)
}

// The name of the etcd release archive.
func (o EtcdInstallOutput) ArchiveName() pulumi.StringOutput {
	return o.ApplyT(func(v *EtcdInstall) pulumi.StringOutput { return v.ArchiveName }).(pulumi.StringOutput)
}

// The remote certificate authority file.
func (o EtcdInstallOutput) CaFile() FileOutput {
	return o.ApplyT(func(v *EtcdInstall) FileOutput { return v.CaFile }).(FileOutput)
}

// The remote certificate file.
func (o EtcdInstallOutput) CertFile() FileOutput {
	return o.ApplyT(func(v *EtcdInstall) FileOutput { return v.CertFile }).(FileOutput)
}

// The directory to store etcd configuration.
func (o EtcdInstallOutput) ConfigurationDirectory() pulumi.StringOutput {
	return o.ApplyT(func(v *EtcdInstall) pulumi.StringOutput { return v.ConfigurationDirectory }).(pulumi.StringOutput)
}

// The command used to create the configuration directory.
func (o EtcdInstallOutput) ConfigurationMkdir() tools.MkdirOutput {
	return o.ApplyT(func(v *EtcdInstall) tools.MkdirOutput { return v.ConfigurationMkdir }).(tools.MkdirOutput)
}

// The directory etcd will use.
func (o EtcdInstallOutput) DataDirectory() pulumi.StringOutput {
	return o.ApplyT(func(v *EtcdInstall) pulumi.StringOutput { return v.DataDirectory }).(pulumi.StringOutput)
}

// The command used to create the data directory.
func (o EtcdInstallOutput) DataMkdir() tools.MkdirOutput {
	return o.ApplyT(func(v *EtcdInstall) tools.MkdirOutput { return v.DataMkdir }).(tools.MkdirOutput)
}

// The etcd download operation.
func (o EtcdInstallOutput) Download() DownloadOutput {
	return o.ApplyT(func(v *EtcdInstall) DownloadOutput { return v.Download }).(DownloadOutput)
}

// The directory where the etcd binary was downloaded to.
func (o EtcdInstallOutput) DownloadDirectory() pulumi.StringOutput {
	return o.ApplyT(func(v *EtcdInstall) pulumi.StringOutput { return v.DownloadDirectory }).(pulumi.StringOutput)
}

// The operation to create the download directory.
func (o EtcdInstallOutput) DownloadMkdir() tools.MkdirOutput {
	return o.ApplyT(func(v *EtcdInstall) tools.MkdirOutput { return v.DownloadMkdir }).(tools.MkdirOutput)
}

// The path to the etcd binary on the remote system.
func (o EtcdInstallOutput) EtcdPath() pulumi.StringOutput {
	return o.ApplyT(func(v *EtcdInstall) pulumi.StringOutput { return v.EtcdPath }).(pulumi.StringOutput)
}

// The path to the etcdctl binary on the remote system.
func (o EtcdInstallOutput) EtcdctlPath() pulumi.StringOutput {
	return o.ApplyT(func(v *EtcdInstall) pulumi.StringOutput { return v.EtcdctlPath }).(pulumi.StringOutput)
}

// Directory to install the `etcd` and `etcdctl` binaries.
func (o EtcdInstallOutput) InstallDirectory() pulumi.StringOutput {
	return o.ApplyT(func(v *EtcdInstall) pulumi.StringOutput { return v.InstallDirectory }).(pulumi.StringOutput)
}

// The operation to create the install directory.
func (o EtcdInstallOutput) InstallMkdir() tools.MkdirOutput {
	return o.ApplyT(func(v *EtcdInstall) tools.MkdirOutput { return v.InstallMkdir }).(tools.MkdirOutput)
}

// IP used to serve client requests and communicate with etcd peers.
func (o EtcdInstallOutput) InternalIp() pulumi.StringOutput {
	return o.ApplyT(func(v *EtcdInstall) pulumi.StringOutput { return v.InternalIp }).(pulumi.StringOutput)
}

// The remote key file.
func (o EtcdInstallOutput) KeyFile() FileOutput {
	return o.ApplyT(func(v *EtcdInstall) FileOutput { return v.KeyFile }).(FileOutput)
}

// The operation to move the etcd binary to the install directory.
func (o EtcdInstallOutput) MvEtcd() tools.MvOutput {
	return o.ApplyT(func(v *EtcdInstall) tools.MvOutput { return v.MvEtcd }).(tools.MvOutput)
}

// The operation to move the etcdctl binary to the install directory.
func (o EtcdInstallOutput) MvEtcdctl() tools.MvOutput {
	return o.ApplyT(func(v *EtcdInstall) tools.MvOutput { return v.MvEtcdctl }).(tools.MvOutput)
}

// The name of the resource.
func (o EtcdInstallOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *EtcdInstall) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The remote systemd service file.
func (o EtcdInstallOutput) SystemdServiceFile() FileOutput {
	return o.ApplyT(func(v *EtcdInstall) FileOutput { return v.SystemdServiceFile }).(FileOutput)
}

// The tar operation.
func (o EtcdInstallOutput) Tar() tools.TarOutput {
	return o.ApplyT(func(v *EtcdInstall) tools.TarOutput { return v.Tar }).(tools.TarOutput)
}

// The url used to download etcd.
func (o EtcdInstallOutput) Url() pulumi.StringOutput {
	return o.ApplyT(func(v *EtcdInstall) pulumi.StringOutput { return v.Url }).(pulumi.StringOutput)
}

// The version of etcd downloaded.
func (o EtcdInstallOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v *EtcdInstall) pulumi.StringOutput { return v.Version }).(pulumi.StringOutput)
}

type EtcdInstallArrayOutput struct{ *pulumi.OutputState }

func (EtcdInstallArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*EtcdInstall)(nil)).Elem()
}

func (o EtcdInstallArrayOutput) ToEtcdInstallArrayOutput() EtcdInstallArrayOutput {
	return o
}

func (o EtcdInstallArrayOutput) ToEtcdInstallArrayOutputWithContext(ctx context.Context) EtcdInstallArrayOutput {
	return o
}

func (o EtcdInstallArrayOutput) Index(i pulumi.IntInput) EtcdInstallOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *EtcdInstall {
		return vs[0].([]*EtcdInstall)[vs[1].(int)]
	}).(EtcdInstallOutput)
}

type EtcdInstallMapOutput struct{ *pulumi.OutputState }

func (EtcdInstallMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*EtcdInstall)(nil)).Elem()
}

func (o EtcdInstallMapOutput) ToEtcdInstallMapOutput() EtcdInstallMapOutput {
	return o
}

func (o EtcdInstallMapOutput) ToEtcdInstallMapOutputWithContext(ctx context.Context) EtcdInstallMapOutput {
	return o
}

func (o EtcdInstallMapOutput) MapIndex(k pulumi.StringInput) EtcdInstallOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *EtcdInstall {
		return vs[0].(map[string]*EtcdInstall)[vs[1].(string)]
	}).(EtcdInstallOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*EtcdInstallInput)(nil)).Elem(), &EtcdInstall{})
	pulumi.RegisterInputType(reflect.TypeOf((*EtcdInstallArrayInput)(nil)).Elem(), EtcdInstallArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*EtcdInstallMapInput)(nil)).Elem(), EtcdInstallMap{})
	pulumi.RegisterOutputType(EtcdInstallOutput{})
	pulumi.RegisterOutputType(EtcdInstallArrayOutput{})
	pulumi.RegisterOutputType(EtcdInstallMapOutput{})
}
