// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.KubernetesTheHardWay.Remote.Inputs
{

    /// <summary>
    /// containerd cri plugin configuration.
    /// </summary>
    public sealed class ContainerdCriPluginConfigurationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// cni configuration.
        /// </summary>
        [Input("cni", required: true)]
        public Inputs.ContainerdCriPluginConfigurationCniArgs Cni { get; set; } = null!;

        /// <summary>
        /// containerd configuration.
        /// </summary>
        [Input("containerd", required: true)]
        public Inputs.ContainerdCriPluginConfigurationContainerdArgs Containerd { get; set; } = null!;

        public ContainerdCriPluginConfigurationArgs()
        {
        }
        public static new ContainerdCriPluginConfigurationArgs Empty => new ContainerdCriPluginConfigurationArgs();
    }
}
