// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.unmango.kubernetesthehardway;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.tls.CertRequest;
import com.pulumi.tls.LocallySignedCert;
import com.pulumi.tls.PrivateKey;
import com.unmango.kubernetesthehardway.CertificateArgs;
import com.unmango.kubernetesthehardway.Utilities;
import java.lang.String;
import javax.annotation.Nullable;

@ResourceType(type="kubernetes-the-hard-way:index:Certificate")
public class Certificate extends com.pulumi.resources.ComponentResource {
    @Export(name="cert", refs={LocallySignedCert.class}, tree="[0]")
    private Output<LocallySignedCert> cert;

    public Output<LocallySignedCert> cert() {
        return this.cert;
    }
    @Export(name="certPem", refs={String.class}, tree="[0]")
    private Output<String> certPem;

    public Output<String> certPem() {
        return this.certPem;
    }
    @Export(name="csr", refs={CertRequest.class}, tree="[0]")
    private Output<CertRequest> csr;

    public Output<CertRequest> csr() {
        return this.csr;
    }
    @Export(name="key", refs={PrivateKey.class}, tree="[0]")
    private Output<PrivateKey> key;

    public Output<PrivateKey> key() {
        return this.key;
    }
    @Export(name="keyPem", refs={String.class}, tree="[0]")
    private Output<String> keyPem;

    public Output<String> keyPem() {
        return this.keyPem;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Certificate(String name) {
        this(name, CertificateArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Certificate(String name, CertificateArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Certificate(String name, CertificateArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        super("kubernetes-the-hard-way:index:Certificate", name, args == null ? CertificateArgs.Empty : args, makeResourceOptions(options, Codegen.empty()), true);
    }

    private static com.pulumi.resources.ComponentResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.ComponentResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.ComponentResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.ComponentResourceOptions.merge(defaultOptions, options, id);
    }

}
