name: Build test image
description: Builds the test docker image for tests

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: examples
        load: true
        tags: kthw:dev
        cache-from: type=gha
        cache-to: type=gha,mode=max
