// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.KubernetesTheHardWay.Remote
{
    /// <summary>
    /// Represents an etcd binary on a remote system.
    /// </summary>
    [KubernetesTheHardWayResourceType("kubernetes-the-hard-way:remote:EtcdInstall")]
    public partial class EtcdInstall : global::Pulumi.ComponentResource
    {
        /// <summary>
        /// The etcd CPU architecture.
        /// </summary>
        [Output("architecture")]
        public Output<UnMango.KubernetesTheHardWay.Remote.Architecture> Architecture { get; private set; } = null!;

        /// <summary>
        /// The name of the etcd release archive.
        /// </summary>
        [Output("archiveName")]
        public Output<string> ArchiveName { get; private set; } = null!;

        /// <summary>
        /// The etcd download operation.
        /// </summary>
        [Output("download")]
        public Output<UnMango.KubernetesTheHardWay.Remote.Download> Download { get; private set; } = null!;

        /// <summary>
        /// The path to the etcd binary on the remote system.
        /// </summary>
        [Output("etcdPath")]
        public Output<string> EtcdPath { get; private set; } = null!;

        /// <summary>
        /// The path to the etcdctl binary on the remote system.
        /// </summary>
        [Output("etcdctlPath")]
        public Output<string> EtcdctlPath { get; private set; } = null!;

        /// <summary>
        /// Directory to install the `etcd` and `etcdctl` binaries.
        /// </summary>
        [Output("installDirectory")]
        public Output<string> InstallDirectory { get; private set; } = null!;

        /// <summary>
        /// The operation to create the install directory.
        /// </summary>
        [Output("installMkdir")]
        public Output<UnMango.KubernetesTheHardWay.Tools.Mkdir> InstallMkdir { get; private set; } = null!;

        /// <summary>
        /// The operation to move the etcd binary to the install directory.
        /// </summary>
        [Output("mvEtcd")]
        public Output<UnMango.KubernetesTheHardWay.Tools.Mv> MvEtcd { get; private set; } = null!;

        /// <summary>
        /// The operation to move the etcdctl binary to the install directory.
        /// </summary>
        [Output("mvEtcdctl")]
        public Output<UnMango.KubernetesTheHardWay.Tools.Mv> MvEtcdctl { get; private set; } = null!;

        /// <summary>
        /// The name of the resource.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The tar operation.
        /// </summary>
        [Output("tar")]
        public Output<UnMango.KubernetesTheHardWay.Tools.Tar> Tar { get; private set; } = null!;

        /// <summary>
        /// The url used to download etcd.
        /// </summary>
        [Output("url")]
        public Output<string> Url { get; private set; } = null!;

        /// <summary>
        /// The version of etcd downloaded.
        /// </summary>
        [Output("version")]
        public Output<string> Version { get; private set; } = null!;


        /// <summary>
        /// Create a EtcdInstall resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public EtcdInstall(string name, EtcdInstallArgs args, ComponentResourceOptions? options = null)
            : base("kubernetes-the-hard-way:remote:EtcdInstall", name, args ?? new EtcdInstallArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/UnstoppableMango",
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }

        public global::Pulumi.Output<UnMango.KubernetesTheHardWay.Tools.Etcdctl> Etcdctl()
            => global::Pulumi.Deployment.Instance.Call<EtcdInstallEtcdctlResult>("kubernetes-the-hard-way:remote:EtcdInstall/etcdctl", CallArgs.Empty, this).Apply(v => v.Result);
    }

    public sealed class EtcdInstallArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The etcd CPU architecture.
        /// </summary>
        [Input("architecture")]
        public Input<UnMango.KubernetesTheHardWay.Remote.Architecture>? Architecture { get; set; }

        /// <summary>
        /// The connection details.
        /// </summary>
        [Input("connection", required: true)]
        public Input<Pulumi.Command.Remote.Inputs.ConnectionArgs> Connection { get; set; } = null!;

        /// <summary>
        /// Directory to install the `etcd` and `etcdctl` binaries.
        /// </summary>
        [Input("installDirectory")]
        public Input<string>? InstallDirectory { get; set; }

        /// <summary>
        /// The version of etcd to install.
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public EtcdInstallArgs()
        {
            InstallDirectory = "/usr/local/bin";
        }
        public static new EtcdInstallArgs Empty => new EtcdInstallArgs();
    }

    /// <summary>
    /// The results of the <see cref="EtcdInstall.Etcdctl"/> method.
    /// </summary>
    [OutputType]
    internal sealed class EtcdInstallEtcdctlResult
    {
        public readonly UnMango.KubernetesTheHardWay.Tools.Etcdctl Result;

        [OutputConstructor]
        private EtcdInstallEtcdctlResult(UnMango.KubernetesTheHardWay.Tools.Etcdctl result)
        {
            Result = result;
        }
    }
}
