// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.KubernetesTheHardWay.Remote
{
    /// <summary>
    /// Create a static pod manifest on a remote system.
    /// </summary>
    [KubernetesTheHardWayResourceType("kubernetes-the-hard-way:remote:StaticPod")]
    public partial class StaticPod : global::Pulumi.ComponentResource
    {
        /// <summary>
        /// The parameters with which to connect to the remote host.
        /// </summary>
        [Output("connection")]
        public Output<Pulumi.Command.Remote.Outputs.Connection> Connection { get; private set; } = null!;

        /// <summary>
        /// The remote manifest file.
        /// </summary>
        [Output("file")]
        public Output<UnMango.KubernetesTheHardWay.Remote.File> File { get; private set; } = null!;

        /// <summary>
        /// The name of the file on the remote system.
        /// </summary>
        [Output("fileName")]
        public Output<string> FileName { get; private set; } = null!;

        /// <summary>
        /// The mkdir operation to ensure /etc/kubernetes/manifests exists.
        /// </summary>
        [Output("mkdir")]
        public Output<UnMango.KubernetesTheHardWay.Tools.Mkdir> Mkdir { get; private set; } = null!;

        /// <summary>
        /// The path to the manifest on the remote system.
        /// </summary>
        [Output("path")]
        public Output<string> Path { get; private set; } = null!;

        /// <summary>
        /// The pod manifest.
        /// </summary>
        [Output("pod")]
        public Output<UnMango.KubernetesTheHardWay.Config.Outputs.PodManifest> Pod { get; private set; } = null!;


        /// <summary>
        /// Create a StaticPod resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public StaticPod(string name, StaticPodArgs args, ComponentResourceOptions? options = null)
            : base("kubernetes-the-hard-way:remote:StaticPod", name, args ?? new StaticPodArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/UnstoppableMango",
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class StaticPodArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The parameters with which to connect to the remote host.
        /// </summary>
        [Input("connection", required: true)]
        public Input<Pulumi.Command.Remote.Inputs.ConnectionArgs> Connection { get; set; } = null!;

        /// <summary>
        /// The name of the file on the remote system.
        /// </summary>
        [Input("fileName")]
        public Input<string>? FileName { get; set; }

        /// <summary>
        /// The pod manifest.
        /// </summary>
        [Input("pod", required: true)]
        public Input<UnMango.KubernetesTheHardWay.Config.Inputs.PodManifestArgs> Pod { get; set; } = null!;

        public StaticPodArgs()
        {
        }
        public static new StaticPodArgs Empty => new StaticPodArgs();
    }
}
