// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

import * as pulumiTls from "@pulumi/tls";
import * as utilities from "../utilities";

export namespace tls {
    /**
     * Node inputs for the PKI.
     */
    export interface ClusterPkiNodeArgs {
        /**
         * The IP address of the node.
         */
        ip?: pulumi.Input<string>;
        role?: pulumi.Input<enums.tls.NodeRole>;
    }

}
