// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.KubernetesTheHardWay.Tools
{
    /// <summary>
    /// Abstraction over the `chmod` utility on a remote system.
    /// </summary>
    [KubernetesTheHardWayResourceType("kubernetes-the-hard-way:tools:Chmod")]
    public partial class Chmod : global::Pulumi.ComponentResource
    {
        /// <summary>
        /// Path to the binary on the remote system. If omitted, the tool is assumed to be on $PATH
        /// </summary>
        [Output("binaryPath")]
        public Output<string> BinaryPath { get; private set; } = null!;

        /// <summary>
        /// Like verbose but report only when a change is made.
        /// </summary>
        [Output("changes")]
        public Output<bool> Changes { get; private set; } = null!;

        /// <summary>
        /// The underlying command
        /// </summary>
        [Output("command")]
        public Output<Pulumi.Command.Remote.Command> Command { get; private set; } = null!;

        /// <summary>
        /// Connection details for the remote system
        /// </summary>
        [Output("connection")]
        public Output<Pulumi.Command.Remote.Outputs.Connection> Connection { get; private set; } = null!;

        /// <summary>
        /// Environment variables
        /// </summary>
        [Output("environment")]
        public Output<ImmutableDictionary<string, string>> Environment { get; private set; } = null!;

        /// <summary>
        /// Corresponds to the [FILE] argument.
        /// </summary>
        [Output("files")]
        public Output<Union<string, ImmutableArray<string>>> Files { get; private set; } = null!;

        /// <summary>
        /// Display help and exit.
        /// </summary>
        [Output("help")]
        public Output<bool> Help { get; private set; } = null!;

        /// <summary>
        /// At what stage(s) in the resource lifecycle should the command be run
        /// </summary>
        [Output("lifecycle")]
        public Output<UnMango.KubernetesTheHardWay.Tools.CommandLifecycle?> Lifecycle { get; private set; } = null!;

        /// <summary>
        /// Modes may be absolute or symbolic. An absolute mode is an octal number...
        /// </summary>
        [Output("mode")]
        public Output<string> Mode { get; private set; } = null!;

        /// <summary>
        /// Do not treat '/' specially (the default).
        /// </summary>
        [Output("noPreserveRoot")]
        public Output<bool> NoPreserveRoot { get; private set; } = null!;

        /// <summary>
        /// Fail to operate recursively on '/'.
        /// </summary>
        [Output("preserveRoot")]
        public Output<bool> PreserveRoot { get; private set; } = null!;

        /// <summary>
        /// Suppress most error messages. Same as `silent`.
        /// </summary>
        [Output("quiet")]
        public Output<bool> Quiet { get; private set; } = null!;

        /// <summary>
        /// Change files and directories recursively.
        /// </summary>
        [Output("recursive")]
        public Output<bool> Recursive { get; private set; } = null!;

        /// <summary>
        /// Use RFILE's mode instead of specifying MODE values. RFILE is always dereferenced if a symbolic link.
        /// </summary>
        [Output("reference")]
        public Output<string?> Reference { get; private set; } = null!;

        /// <summary>
        /// Suppress most error messages. Same as `quiet`.
        /// </summary>
        [Output("silent")]
        public Output<bool> Silent { get; private set; } = null!;

        /// <summary>
        /// TODO
        /// </summary>
        [Output("stderr")]
        public Output<string> Stderr { get; private set; } = null!;

        /// <summary>
        /// TODO
        /// </summary>
        [Output("stdin")]
        public Output<string?> Stdin { get; private set; } = null!;

        /// <summary>
        /// TODO
        /// </summary>
        [Output("stdout")]
        public Output<string> Stdout { get; private set; } = null!;

        /// <summary>
        /// TODO
        /// </summary>
        [Output("triggers")]
        public Output<ImmutableArray<object>> Triggers { get; private set; } = null!;

        /// <summary>
        /// Output version information and exit.
        /// </summary>
        [Output("version")]
        public Output<bool> Version { get; private set; } = null!;


        /// <summary>
        /// Create a Chmod resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Chmod(string name, ChmodArgs args, ComponentResourceOptions? options = null)
            : base("kubernetes-the-hard-way:tools:Chmod", name, args ?? new ChmodArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/UnstoppableMango",
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ChmodArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Path to the binary on the remote system. If omitted, the tool is assumed to be on $PATH
        /// </summary>
        [Input("binaryPath")]
        public Input<string>? BinaryPath { get; set; }

        /// <summary>
        /// Like verbose but report only when a change is made.
        /// </summary>
        [Input("changes")]
        public Input<bool>? Changes { get; set; }

        /// <summary>
        /// Connection details for the remote system
        /// </summary>
        [Input("connection", required: true)]
        public Input<Pulumi.Command.Remote.Inputs.ConnectionArgs> Connection { get; set; } = null!;

        [Input("environment")]
        private InputMap<string>? _environment;

        /// <summary>
        /// Environment variables
        /// </summary>
        public InputMap<string> Environment
        {
            get => _environment ?? (_environment = new InputMap<string>());
            set => _environment = value;
        }

        /// <summary>
        /// Corresponds to the [FILE] argument.
        /// </summary>
        [Input("files", required: true)]
        public InputUnion<string, ImmutableArray<string>> Files { get; set; } = null!;

        /// <summary>
        /// Display help and exit.
        /// </summary>
        [Input("help")]
        public Input<bool>? Help { get; set; }

        /// <summary>
        /// At what stage(s) in the resource lifecycle should the command be run
        /// </summary>
        [Input("lifecycle")]
        public UnMango.KubernetesTheHardWay.Tools.CommandLifecycle? Lifecycle { get; set; }

        /// <summary>
        /// Modes may be absolute or symbolic. An absolute mode is an octal number...
        /// </summary>
        [Input("mode", required: true)]
        public Input<string> Mode { get; set; } = null!;

        /// <summary>
        /// Do not treat '/' specially (the default).
        /// </summary>
        [Input("noPreserveRoot")]
        public Input<bool>? NoPreserveRoot { get; set; }

        /// <summary>
        /// Fail to operate recursively on '/'.
        /// </summary>
        [Input("preserveRoot")]
        public Input<bool>? PreserveRoot { get; set; }

        /// <summary>
        /// Suppress most error messages. Same as `silent`.
        /// </summary>
        [Input("quiet")]
        public Input<bool>? Quiet { get; set; }

        /// <summary>
        /// Change files and directories recursively.
        /// </summary>
        [Input("recursive")]
        public Input<bool>? Recursive { get; set; }

        /// <summary>
        /// Use RFILE's mode instead of specifying MODE values. RFILE is always dereferenced if a symbolic link.
        /// </summary>
        [Input("reference")]
        public Input<string>? Reference { get; set; }

        /// <summary>
        /// Suppress most error messages. Same as `quiet`.
        /// </summary>
        [Input("silent")]
        public Input<bool>? Silent { get; set; }

        /// <summary>
        /// TODO
        /// </summary>
        [Input("stdin")]
        public Input<string>? Stdin { get; set; }

        [Input("triggers")]
        private InputList<object>? _triggers;

        /// <summary>
        /// TODO
        /// </summary>
        public InputList<object> Triggers
        {
            get => _triggers ?? (_triggers = new InputList<object>());
            set => _triggers = value;
        }

        /// <summary>
        /// Output version information and exit.
        /// </summary>
        [Input("version")]
        public Input<bool>? Version { get; set; }

        public ChmodArgs()
        {
        }
        public static new ChmodArgs Empty => new ChmodArgs();
    }
}
