// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace UnMango.KubernetesTheHardWay.Tools
{
    [EnumType]
    public readonly struct EtcdctlCommand : IEquatable<EtcdctlCommand>
    {
        private readonly string _value;

        private EtcdctlCommand(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static EtcdctlCommand Member { get; } = new EtcdctlCommand("member");
        public static EtcdctlCommand List { get; } = new EtcdctlCommand("list");

        public static bool operator ==(EtcdctlCommand left, EtcdctlCommand right) => left.Equals(right);
        public static bool operator !=(EtcdctlCommand left, EtcdctlCommand right) => !left.Equals(right);

        public static explicit operator string(EtcdctlCommand value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is EtcdctlCommand other && Equals(other);
        public bool Equals(EtcdctlCommand other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct SystemctlCommand : IEquatable<SystemctlCommand>
    {
        private readonly string _value;

        private SystemctlCommand(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static SystemctlCommand Daemon_reload { get; } = new SystemctlCommand("daemon-reload");
        public static SystemctlCommand Disable { get; } = new SystemctlCommand("disable");
        public static SystemctlCommand Enable { get; } = new SystemctlCommand("enable");
        public static SystemctlCommand Start { get; } = new SystemctlCommand("start");
        public static SystemctlCommand Stop { get; } = new SystemctlCommand("stop");

        public static bool operator ==(SystemctlCommand left, SystemctlCommand right) => left.Equals(right);
        public static bool operator !=(SystemctlCommand left, SystemctlCommand right) => !left.Equals(right);

        public static explicit operator string(SystemctlCommand value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is SystemctlCommand other && Equals(other);
        public bool Equals(SystemctlCommand other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
