// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.KubernetesTheHardWay.Tools
{
    /// <summary>
    /// Abstraction over the `mv` utility on a remote system.
    /// </summary>
    [KubernetesTheHardWayResourceType("kubernetes-the-hard-way:tools:Mv")]
    public partial class Mv : global::Pulumi.ComponentResource
    {
        /// <summary>
        /// Corresponds to the `-b` and `--backup` options depending on whether [CONTROL] is supplied.
        /// </summary>
        [Output("backup")]
        public Output<bool> Backup { get; private set; } = null!;

        /// <summary>
        /// Path to the binary on the remote system. If omitted, the tool is assumed to be on $PATH
        /// </summary>
        [Output("binaryPath")]
        public Output<string> BinaryPath { get; private set; } = null!;

        /// <summary>
        /// The underlying command
        /// </summary>
        [Output("command")]
        public Output<Pulumi.Command.Remote.Command> Command { get; private set; } = null!;

        /// <summary>
        /// Connection details for the remote system
        /// </summary>
        [Output("connection")]
        public Output<Pulumi.Command.Remote.Outputs.Connection> Connection { get; private set; } = null!;

        /// <summary>
        /// Corresponds to the `--context` option.
        /// </summary>
        [Output("context")]
        public Output<bool> Context { get; private set; } = null!;

        /// <summary>
        /// Corresponds to the [CONTROL] argument for the `--backup` option.
        /// </summary>
        [Output("control")]
        public Output<bool?> Control { get; private set; } = null!;

        /// <summary>
        /// Corresponds to the [DEST] argument.
        /// </summary>
        [Output("dest")]
        public Output<string?> Dest { get; private set; } = null!;

        /// <summary>
        /// Corresponds to the [DIRECTORY] argument.
        /// </summary>
        [Output("directory")]
        public Output<string?> Directory { get; private set; } = null!;

        /// <summary>
        /// Environment variables
        /// </summary>
        [Output("environment")]
        public Output<ImmutableDictionary<string, string>> Environment { get; private set; } = null!;

        /// <summary>
        /// Corresponds to the `--force` option.
        /// </summary>
        [Output("force")]
        public Output<bool> Force { get; private set; } = null!;

        /// <summary>
        /// At what stage(s) in the resource lifecycle should the command be run
        /// </summary>
        [Output("lifecycle")]
        public Output<UnMango.KubernetesTheHardWay.Tools.CommandLifecycle?> Lifecycle { get; private set; } = null!;

        /// <summary>
        /// Corresponds to the `--no-clobber` option.
        /// </summary>
        [Output("noClobber")]
        public Output<bool> NoClobber { get; private set; } = null!;

        /// <summary>
        /// Corresponds to the `--no-target-directory` option.
        /// </summary>
        [Output("noTargetDirectory")]
        public Output<bool> NoTargetDirectory { get; private set; } = null!;

        /// <summary>
        /// Corresponds to the [SOURCE] argument.
        /// </summary>
        [Output("source")]
        public Output<Union<string, ImmutableArray<string>>> Source { get; private set; } = null!;

        /// <summary>
        /// TODO
        /// </summary>
        [Output("stderr")]
        public Output<string> Stderr { get; private set; } = null!;

        /// <summary>
        /// TODO
        /// </summary>
        [Output("stdin")]
        public Output<string?> Stdin { get; private set; } = null!;

        /// <summary>
        /// TODO
        /// </summary>
        [Output("stdout")]
        public Output<string> Stdout { get; private set; } = null!;

        /// <summary>
        /// Corresponds to the `--strip-trailing-slashes` option.
        /// </summary>
        [Output("stripTrailingSlashes")]
        public Output<bool> StripTrailingSlashes { get; private set; } = null!;

        /// <summary>
        /// Corresponds to the `--suffix` option.
        /// </summary>
        [Output("suffix")]
        public Output<string?> Suffix { get; private set; } = null!;

        /// <summary>
        /// Corresponds to the `--target-directory` option.
        /// </summary>
        [Output("targetDirectory")]
        public Output<bool?> TargetDirectory { get; private set; } = null!;

        /// <summary>
        /// TODO
        /// </summary>
        [Output("triggers")]
        public Output<ImmutableArray<object>> Triggers { get; private set; } = null!;

        /// <summary>
        /// Corresponds to the `--update` option.
        /// </summary>
        [Output("update")]
        public Output<bool> Update { get; private set; } = null!;

        /// <summary>
        /// Corresponds to the `--verbose` option.
        /// </summary>
        [Output("verbose")]
        public Output<bool> Verbose { get; private set; } = null!;


        /// <summary>
        /// Create a Mv resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Mv(string name, MvArgs args, ComponentResourceOptions? options = null)
            : base("kubernetes-the-hard-way:tools:Mv", name, args ?? new MvArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/UnstoppableMango",
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class MvArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Corresponds to the `-b` and `--backup` options depending on whether [CONTROL] is supplied.
        /// </summary>
        [Input("backup")]
        public bool? Backup { get; set; }

        /// <summary>
        /// Path to the binary on the remote system. If omitted, the tool is assumed to be on $PATH
        /// </summary>
        [Input("binaryPath")]
        public Input<string>? BinaryPath { get; set; }

        /// <summary>
        /// Connection details for the remote system
        /// </summary>
        [Input("connection", required: true)]
        public Input<Pulumi.Command.Remote.Inputs.ConnectionArgs> Connection { get; set; } = null!;

        /// <summary>
        /// Corresponds to the `--context` option.
        /// </summary>
        [Input("context")]
        public Input<bool>? Context { get; set; }

        /// <summary>
        /// Corresponds to the [CONTROL] argument for the `--backup` option.
        /// </summary>
        [Input("control")]
        public Input<bool>? Control { get; set; }

        /// <summary>
        /// Corresponds to the [DEST] argument.
        /// </summary>
        [Input("dest")]
        public Input<string>? Dest { get; set; }

        /// <summary>
        /// Corresponds to the [DIRECTORY] argument.
        /// </summary>
        [Input("directory")]
        public Input<string>? Directory { get; set; }

        [Input("environment")]
        private InputMap<string>? _environment;

        /// <summary>
        /// Environment variables
        /// </summary>
        public InputMap<string> Environment
        {
            get => _environment ?? (_environment = new InputMap<string>());
            set => _environment = value;
        }

        /// <summary>
        /// Corresponds to the `--force` option.
        /// </summary>
        [Input("force")]
        public Input<bool>? Force { get; set; }

        /// <summary>
        /// At what stage(s) in the resource lifecycle should the command be run
        /// </summary>
        [Input("lifecycle")]
        public UnMango.KubernetesTheHardWay.Tools.CommandLifecycle? Lifecycle { get; set; }

        /// <summary>
        /// Corresponds to the `--no-clobber` option.
        /// </summary>
        [Input("noClobber")]
        public Input<bool>? NoClobber { get; set; }

        /// <summary>
        /// Corresponds to the `--no-target-directory` option.
        /// </summary>
        [Input("noTargetDirectory")]
        public Input<bool>? NoTargetDirectory { get; set; }

        /// <summary>
        /// Corresponds to the [SOURCE] argument.
        /// </summary>
        [Input("source", required: true)]
        public InputUnion<string, ImmutableArray<string>> Source { get; set; } = null!;

        /// <summary>
        /// TODO
        /// </summary>
        [Input("stdin")]
        public Input<string>? Stdin { get; set; }

        /// <summary>
        /// Corresponds to the `--strip-trailing-slashes` option.
        /// </summary>
        [Input("stripTrailingSlashes")]
        public Input<bool>? StripTrailingSlashes { get; set; }

        /// <summary>
        /// Corresponds to the `--suffix` option.
        /// </summary>
        [Input("suffix")]
        public Input<string>? Suffix { get; set; }

        /// <summary>
        /// Corresponds to the `--target-directory` option.
        /// </summary>
        [Input("targetDirectory")]
        public Input<bool>? TargetDirectory { get; set; }

        [Input("triggers")]
        private InputList<object>? _triggers;

        /// <summary>
        /// TODO
        /// </summary>
        public InputList<object> Triggers
        {
            get => _triggers ?? (_triggers = new InputList<object>());
            set => _triggers = value;
        }

        /// <summary>
        /// Corresponds to the `--update` option.
        /// </summary>
        [Input("update")]
        public Input<bool>? Update { get; set; }

        /// <summary>
        /// Corresponds to the `--verbose` option.
        /// </summary>
        [Input("verbose")]
        public Input<bool>? Verbose { get; set; }

        public MvArgs()
        {
        }
        public static new MvArgs Empty => new MvArgs();
    }
}
