// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.unmango.kubernetesthehardway.config.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * containerd cri runc plugin configuration.
 * 
 */
public final class ContainerdCriPluginConfigurationContainerdRuncOptions extends com.pulumi.resources.InvokeArgs {

    public static final ContainerdCriPluginConfigurationContainerdRuncOptions Empty = new ContainerdCriPluginConfigurationContainerdRuncOptions();

    /**
     * SystemdCgroup
     * 
     */
    @Import(name="systemdCgroup")
    private @Nullable Boolean systemdCgroup;

    /**
     * @return SystemdCgroup
     * 
     */
    public Optional<Boolean> systemdCgroup() {
        return Optional.ofNullable(this.systemdCgroup);
    }

    private ContainerdCriPluginConfigurationContainerdRuncOptions() {}

    private ContainerdCriPluginConfigurationContainerdRuncOptions(ContainerdCriPluginConfigurationContainerdRuncOptions $) {
        this.systemdCgroup = $.systemdCgroup;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ContainerdCriPluginConfigurationContainerdRuncOptions defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ContainerdCriPluginConfigurationContainerdRuncOptions $;

        public Builder() {
            $ = new ContainerdCriPluginConfigurationContainerdRuncOptions();
        }

        public Builder(ContainerdCriPluginConfigurationContainerdRuncOptions defaults) {
            $ = new ContainerdCriPluginConfigurationContainerdRuncOptions(Objects.requireNonNull(defaults));
        }

        /**
         * @param systemdCgroup SystemdCgroup
         * 
         * @return builder
         * 
         */
        public Builder systemdCgroup(@Nullable Boolean systemdCgroup) {
            $.systemdCgroup = systemdCgroup;
            return this;
        }

        public ContainerdCriPluginConfigurationContainerdRuncOptions build() {
            return $;
        }
    }

}
