// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.unmango.kubernetesthehardway.config.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetKubeconfigPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetKubeconfigPlainArgs Empty = new GetKubeconfigPlainArgs();

    /**
     * Certificate authority data.
     * 
     */
    @Import(name="caPem", required=true)
    private String caPem;

    /**
     * @return Certificate authority data.
     * 
     */
    public String caPem() {
        return this.caPem;
    }

    /**
     * The PEM encoded certificate data of the client.
     * 
     */
    @Import(name="clientCert", required=true)
    private String clientCert;

    /**
     * @return The PEM encoded certificate data of the client.
     * 
     */
    public String clientCert() {
        return this.clientCert;
    }

    /**
     * The PEM encoded private key data of the client.
     * 
     */
    @Import(name="clientKey", required=true)
    private String clientKey;

    /**
     * @return The PEM encoded private key data of the client.
     * 
     */
    public String clientKey() {
        return this.clientKey;
    }

    /**
     * A name to identify the cluster.
     * 
     */
    @Import(name="clusterName", required=true)
    private String clusterName;

    /**
     * @return A name to identify the cluster.
     * 
     */
    public String clusterName() {
        return this.clusterName;
    }

    /**
     * A name to use for the kubeconfig context
     * 
     */
    @Import(name="contextName")
    private @Nullable String contextName;

    /**
     * @return A name to use for the kubeconfig context
     * 
     */
    public Optional<String> contextName() {
        return Optional.ofNullable(this.contextName);
    }

    /**
     * The address and port of the Kubernetes API server.
     * 
     */
    @Import(name="server", required=true)
    private String server;

    /**
     * @return The address and port of the Kubernetes API server.
     * 
     */
    public String server() {
        return this.server;
    }

    /**
     * The username of the user
     * 
     */
    @Import(name="username", required=true)
    private String username;

    /**
     * @return The username of the user
     * 
     */
    public String username() {
        return this.username;
    }

    private GetKubeconfigPlainArgs() {}

    private GetKubeconfigPlainArgs(GetKubeconfigPlainArgs $) {
        this.caPem = $.caPem;
        this.clientCert = $.clientCert;
        this.clientKey = $.clientKey;
        this.clusterName = $.clusterName;
        this.contextName = $.contextName;
        this.server = $.server;
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetKubeconfigPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetKubeconfigPlainArgs $;

        public Builder() {
            $ = new GetKubeconfigPlainArgs();
        }

        public Builder(GetKubeconfigPlainArgs defaults) {
            $ = new GetKubeconfigPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param caPem Certificate authority data.
         * 
         * @return builder
         * 
         */
        public Builder caPem(String caPem) {
            $.caPem = caPem;
            return this;
        }

        /**
         * @param clientCert The PEM encoded certificate data of the client.
         * 
         * @return builder
         * 
         */
        public Builder clientCert(String clientCert) {
            $.clientCert = clientCert;
            return this;
        }

        /**
         * @param clientKey The PEM encoded private key data of the client.
         * 
         * @return builder
         * 
         */
        public Builder clientKey(String clientKey) {
            $.clientKey = clientKey;
            return this;
        }

        /**
         * @param clusterName A name to identify the cluster.
         * 
         * @return builder
         * 
         */
        public Builder clusterName(String clusterName) {
            $.clusterName = clusterName;
            return this;
        }

        /**
         * @param contextName A name to use for the kubeconfig context
         * 
         * @return builder
         * 
         */
        public Builder contextName(@Nullable String contextName) {
            $.contextName = contextName;
            return this;
        }

        /**
         * @param server The address and port of the Kubernetes API server.
         * 
         * @return builder
         * 
         */
        public Builder server(String server) {
            $.server = server;
            return this;
        }

        /**
         * @param username The username of the user
         * 
         * @return builder
         * 
         */
        public Builder username(String username) {
            $.username = username;
            return this;
        }

        public GetKubeconfigPlainArgs build() {
            if ($.caPem == null) {
                throw new MissingRequiredPropertyException("GetKubeconfigPlainArgs", "caPem");
            }
            if ($.clientCert == null) {
                throw new MissingRequiredPropertyException("GetKubeconfigPlainArgs", "clientCert");
            }
            if ($.clientKey == null) {
                throw new MissingRequiredPropertyException("GetKubeconfigPlainArgs", "clientKey");
            }
            if ($.clusterName == null) {
                throw new MissingRequiredPropertyException("GetKubeconfigPlainArgs", "clusterName");
            }
            if ($.server == null) {
                throw new MissingRequiredPropertyException("GetKubeconfigPlainArgs", "server");
            }
            if ($.username == null) {
                throw new MissingRequiredPropertyException("GetKubeconfigPlainArgs", "username");
            }
            return $;
        }
    }

}
