// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.unmango.kubernetesthehardway.config.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class KubeconfigKubeProxyOptionsArgs extends com.pulumi.resources.ResourceArgs {

    public static final KubeconfigKubeProxyOptionsArgs Empty = new KubeconfigKubeProxyOptionsArgs();

    @Import(name="publicIp")
    private @Nullable Output<String> publicIp;

    public Optional<Output<String>> publicIp() {
        return Optional.ofNullable(this.publicIp);
    }

    @Import(name="type")
    private @Nullable Output<String> type;

    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    private KubeconfigKubeProxyOptionsArgs() {}

    private KubeconfigKubeProxyOptionsArgs(KubeconfigKubeProxyOptionsArgs $) {
        this.publicIp = $.publicIp;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(KubeconfigKubeProxyOptionsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private KubeconfigKubeProxyOptionsArgs $;

        public Builder() {
            $ = new KubeconfigKubeProxyOptionsArgs();
        }

        public Builder(KubeconfigKubeProxyOptionsArgs defaults) {
            $ = new KubeconfigKubeProxyOptionsArgs(Objects.requireNonNull(defaults));
        }

        public Builder publicIp(@Nullable Output<String> publicIp) {
            $.publicIp = publicIp;
            return this;
        }

        public Builder publicIp(String publicIp) {
            return publicIp(Output.of(publicIp));
        }

        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        public Builder type(String type) {
            return type(Output.of(type));
        }

        public KubeconfigKubeProxyOptionsArgs build() {
            $.type = Codegen.stringProp("type").output().arg($.type).getNullable();
            return $;
        }
    }

}
