name: pull-request

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - CHANGELOG.md

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        language:
          - nodejs
          - python
          - dotnet
          - go
          - java
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Languages & Frameworks
        uses: ./.github/actions/install
        with:
          skip_dotnet_and_java: ${{ matrix.language != 'dotnet' && matrix.language != 'java' }}

      - run: make ensure

      - name: Build binaries
        run: make provider

      # Enable when we actually have some tests
      # - name: Test Provider Library
      #   run: |
      #     set -euo pipefail
      #     cd provider && go test -v -json -coverprofile="coverage.txt" -coverpkg=./... -timeout 1h -parallel 16 ./... 2>&1 | tee /tmp/gotest.log | gotestfmt

      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v4
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Install Node dependencies
        run: yarn global add typescript

      - name: Install Python deps
        if: matrix.language == 'python'
        run: |-
          pip3 install virtualenv==20.0.23
          pip3 install pipenv

      - name: Install gotestfmt
        uses: jaxxstorm/action-install-gh-release@v1.11.0
        with:
          tag: v2.5.0
          repo: GoTestTools/gotestfmt

      - name: Install dependencies
        run: make install_${{ matrix.language }}_sdk

      - name: Run short tests
        run: |
          set -euo pipefail
          cd examples && go test -v -json -cover -timeout 15m -short -tags=${{ matrix.language }} -parallel 16 . 2>&1 | tee /tmp/gotest.log | gotestfmt

  lint_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Lint actions
        uses: reviewdog/action-actionlint@v1.36.0
        with:
          actionlint_flags: "-config-file .actionlint.yml"
