name: release

on:
  push:
    tags:
      - v*.*.*

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - id: version
        name: Calculate build version
        # Remove "v" if present
        run: echo "version=${GITHUB_REF_NAME/v/}" >> "$GITHUB_OUTPUT"
    outputs:
      version: ${{ steps.version.outputs.version }}

  build_test:
    uses: ./.github/workflows/build-test.yml
    needs: version
    secrets: inherit
    with:
      ref: ${{ github.ref }}
      version: ${{ needs.version.outputs.version }}

  publish:
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    needs:
      - build_test
      - version
    with:
      ref: ${{ github.ref }}
      version: ${{ needs.version.outputs.version }}
      prerelease: ${{ contains(github.ref_name,'-') }}
