// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

import * as pulumiCommand from "@pulumi/command";

export function installOn(args?: InstallOnArgs, opts?: pulumi.InvokeOptions): Promise<InstallOnResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("kubernetes-the-hard-way:index:installOn", {
        "connection": args.connection ? pulumiCommand.types.input.remote.connectionProvideDefaults(args.connection) : undefined,
    }, opts);
}

export interface InstallOnArgs {
    connection?: pulumiCommand.types.input.remote.Connection;
}

export interface InstallOnResult {
    readonly file?: string;
}
export function installOnOutput(args?: InstallOnOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<InstallOnResult> {
    return pulumi.output(args).apply((a: any) => installOn(a, opts))
}

export interface InstallOnOutputArgs {
    connection?: pulumi.Input<pulumiCommand.types.input.remote.ConnectionArgs>;
}
