// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UnMango.KubernetesTheHardWay.Tls.Outputs
{

    /// <summary>
    /// TODO
    /// </summary>
    [OutputType]
    public sealed class ClusterPkiNode
    {
        /// <summary>
        /// The IP address of the node
        /// </summary>
        public readonly string? Ip;
        /// <summary>
        /// The role a node should be configured for
        /// </summary>
        public readonly UnMango.KubernetesTheHardWay.Tls.NodeRole? Role;

        [OutputConstructor]
        private ClusterPkiNode(
            string? ip,

            UnMango.KubernetesTheHardWay.Tls.NodeRole? role)
        {
            Ip = ip;
            Role = role;
        }
    }
}
